[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
ggus = { version = "*", path = "../ggus" }

digit-layout = "0.0"
memmap2 = "0.9"
regex = "1.10"
clap = { version = "4.5", features = ["derive"] }
itertools = "0.13.0"
