[alias]
xtask = "run --package xtask --release --"
debug = "run --package xtask --"
show = "xtask show"
split = "xtask split"
merge = "xtask merge"
cast = "xtask cast"
convert = "xtask convert"
to-llama = "xtask to-llama"
set-meta = "xtask set-meta"
